---
sonarr_enabled: true
sonarr_available_externally: true

# directories
sonarr_data_directory: "{{ docker_home }}/sonarr/config"
sonarr_tv_directory: "{{ tv_root }}"
sonarr_download_directory: "{{ downloads_root }}"

# uid / gid
sonarr_user_id: "0"
sonarr_group_id: "0"

# network
sonarr_port: "8989"
sonarr_hostname: "sonarr"

# specs
sonarr_memory: 1g
